/**
 * Core interface definitions and type system for modular architecture refactor
 * 
 * This file defines the foundational interfaces and types that enable the modular
 * architecture, including IStrategy, IExecutionEngine, IExchangeAdapter, and IStateMachine.
 */

import type { StrategyConfig } from './config.js';

// ============================================================================
// TRADING SIGNAL TYPES
// ============================================================================

/**
 * Trading signal generated by strategy components
 */
export interface TradingSignal {
  /** Trading direction */
  direction: 'long' | 'short' | 'skip';
  /** Confidence level (0-1) */
  confidence: number;
  /** Human-readable reasoning for the signal */
  reasoning: string;
  /** Additional metadata for debugging and analysis */
  metadata: Record<string, any>;
  /** Timestamp when signal was generated */
  timestamp?: Date;
}

/**
 * Market context data required for signal generation
 */
export interface MarketContext {
  /** Current market price */
  currentPrice: number;
  /** Available balance */
  balance: number;
  /** Current position (if any) */
  currentPosition?: Position;
  /** Market volatility indicators */
  volatility?: {
    atr?: number;
    bbWidth?: number;
    volRatio?: number;
  };
  /** Orderbook data */
  orderbook?: {
    bestBid: number;
    bestAsk: number;
    spread: number;
    imbalance: number;
  };
  /** Additional market indicators */
  indicators?: Record<string, any>;
}

// ============================================================================
// EXECUTION TYPES
// ============================================================================

/**
 * Context required for order execution
 */
export interface ExecutionContext {
  /** Trading symbol */
  symbol: string;
  /** Available balance */
  balance: number;
  /** Current position (if any) */
  currentPosition?: Position;
  /** Risk management limits */
  riskLimits: RiskLimits;
  /** Market data for execution decisions */
  marketData?: MarketContext;
}

/**
 * Request for placing an order
 */
export interface OrderRequest {
  /** Trading symbol */
  symbol: string;
  /** Order side */
  side: 'buy' | 'sell';
  /** Order price */
  price: number;
  /** Order size */
  size: number;
  /** Reduce-only flag */
  reduceOnly?: boolean;
  /** Time in force */
  timeInForce?: TimeInForce;
  /** Order type */
  type?: OrderType;
}

/**
 * Result of order execution
 */
export interface ExecutionResult {
  /** Whether execution was successful */
  success: boolean;
  /** Order ID if successful */
  orderId?: string;
  /** Error message if failed */
  error?: string;
  /** Additional execution metadata */
  metadata: Record<string, any>;
  /** Timestamp of execution */
  timestamp: Date;
}

/**
 * Result of order placement
 */
export interface OrderResult {
  /** Whether order placement was successful */
  success: boolean;
  /** Order ID if successful */
  orderId?: string;
  /** Error message if failed */
  error?: string;
  /** Order details */
  order?: Order;
}

// ============================================================================
// POSITION AND ORDER TYPES
// ============================================================================

/**
 * Trading position information
 */
export interface Position {
  /** Trading symbol */
  symbol: string;
  /** Position side */
  side: 'long' | 'short' | 'neutral';
  /** Position size */
  size: number;
  /** Entry price */
  entryPrice: number;
  /** Unrealized PnL */
  unrealizedPnl: number;
  /** Position timestamp */
  timestamp?: Date;
  /** Additional position metadata */
  metadata?: Record<string, any>;
}

/**
 * Order information
 */
export interface Order {
  /** Order ID */
  id: string;
  /** Trading symbol */
  symbol: string;
  /** Order side */
  side: 'buy' | 'sell';
  /** Order price */
  price: number;
  /** Order size */
  size: number;
  /** Order status */
  status: OrderStatus;
  /** Order timestamp */
  timestamp: Date;
  /** Order type */
  type?: OrderType;
  /** Time in force */
  timeInForce?: TimeInForce;
  /** Filled size */
  filledSize?: number;
  /** Remaining size */
  remainingSize?: number;
}

/**
 * Orderbook data structure
 */
export interface Orderbook {
  /** Best bid price */
  bestBid: number;
  /** Best ask price */
  bestAsk: number;
  /** Bid levels */
  bids: [number, number][];
  /** Ask levels */
  asks: [number, number][];
  /** Timestamp */
  timestamp?: Date;
}

/**
 * Raw trade data
 */
export interface RawTrade {
  /** Trade side */
  side: 'buy' | 'sell';
  /** Trade price */
  price: number;
  /** Trade size */
  size: number;
  /** Trade timestamp */
  timestamp: number;
}

// ============================================================================
// ENUMS AND CONSTANTS
// ============================================================================

/**
 * Order status enumeration
 */
export type OrderStatus = 'pending' | 'filled' | 'cancelled' | 'rejected' | 'partially_filled';

/**
 * Order type enumeration
 */
export type OrderType = 'market' | 'limit' | 'stop' | 'stop_limit';

/**
 * Time in force enumeration
 */
export type TimeInForce = 'GTC' | 'IOC' | 'FOK' | 'post-only';

/**
 * Bot state enumeration
 */
export type BotState = 'IDLE' | 'PENDING_ENTRY' | 'IN_POSITION' | 'PENDING_EXIT' | 'ERROR' | 'STOPPED';

/**
 * Trading regime enumeration
 */
export type TradingRegime = 'TREND_UP' | 'TREND_DOWN' | 'SIDEWAY' | 'HIGH_VOLATILITY';

// ============================================================================
// RISK MANAGEMENT TYPES
// ============================================================================

/**
 * Risk management limits
 */
export interface RiskLimits {
  /** Maximum position size */
  maxPositionSize: number;
  /** Maximum loss per trade */
  maxLossPerTrade: number;
  /** Maximum daily loss */
  maxDailyLoss: number;
  /** Maximum drawdown percentage */
  maxDrawdown: number;
  /** Maximum leverage */
  maxLeverage?: number;
  /** Position size limits by symbol */
  symbolLimits?: Record<string, number>;
}

/**
 * Risk validation result
 */
export interface RiskValidationResult {
  /** Whether risk check passed */
  passed: boolean;
  /** Reason for failure (if any) */
  reason?: string;
  /** Suggested adjustments */
  suggestions?: string[];
}

// ============================================================================
// STATE MACHINE TYPES
// ============================================================================

/**
 * State transition event
 */
export interface StateEvent {
  /** Event type */
  type: string;
  /** Event payload */
  payload: any;
  /** Event timestamp */
  timestamp: number;
  /** Event source */
  source?: string;
}

/**
 * State transition record
 */
export interface StateTransition {
  /** Previous state */
  from: BotState;
  /** New state */
  to: BotState;
  /** Triggering event */
  event: StateEvent;
  /** Transition timestamp */
  timestamp: Date;
  /** Transition metadata */
  metadata?: Record<string, any>;
}

// ============================================================================
// EVENT SYSTEM TYPES
// ============================================================================

/**
 * Event data structure
 */
export interface EventData {
  /** Event type */
  type: string;
  /** Event payload */
  payload: any;
  /** Event timestamp */
  timestamp: Date;
  /** Event source */
  source: string;
  /** Event metadata */
  metadata?: Record<string, any>;
}

/**
 * Event handler function type
 */
export type EventHandler<T = any> = (data: T) => void | Promise<void>;

/**
 * Event subscription
 */
export interface EventSubscription {
  /** Subscription ID */
  id: string;
  /** Event type */
  eventType: string;
  /** Event handler */
  handler: EventHandler;
  /** Subscription options */
  options?: {
    once?: boolean;
    priority?: number;
  };
}

// ============================================================================
// CORE INTERFACES
// ============================================================================

/**
 * Strategy interface for generating trading signals
 * 
 * Strategies are completely isolated from exchange implementations and
 * only generate signals based on market data.
 */
export interface IStrategy {
  /**
   * Generate a trading signal for the given symbol and market context
   */
  getSignal(symbol: string, context: MarketContext): Promise<TradingSignal>;
  
  /**
   * Invalidate any cached signals
   */
  invalidateCache(): void;
  
  /**
   * Configure the strategy with new parameters
   */
  configure(config: StrategyConfig): void;
  
  /**
   * Get strategy metadata and status
   */
  getStatus(): StrategyStatus;
}

/**
 * Execution engine interface for handling order placement and risk management
 * 
 * The ExecutionEngine is the only component that directly interacts with
 * exchange adapters, serving as middleware between strategies and exchanges.
 */
export interface IExecutionEngine {
  /**
   * Execute a trading signal with risk management
   */
  executeSignal(signal: TradingSignal, context: ExecutionContext): Promise<ExecutionResult>;
  
  /**
   * Place an order directly
   */
  placeOrder(orderRequest: OrderRequest): Promise<OrderResult>;
  
  /**
   * Cancel an order
   */
  cancelOrder(orderId: string, symbol: string): Promise<boolean>;
  
  /**
   * Cancel all orders for a symbol
   */
  cancelAllOrders(symbol: string): Promise<boolean>;
  
  /**
   * Get current positions
   */
  getPositions(symbol?: string): Promise<Position[]>;
  
  /**
   * Get account balance
   */
  getBalance(): Promise<number>;
  
  /**
   * Set the exchange adapter to use
   */
  setAdapter(adapter: IExchangeAdapter): void;
  
  /**
   * Validate risk limits for a potential trade
   */
  validateRisk(signal: TradingSignal, context: ExecutionContext): Promise<RiskValidationResult>;
}

/**
 * Exchange adapter interface for abstracting exchange-specific implementations
 * 
 * Adapters normalize data formats and API calls across different exchanges.
 */
export interface IExchangeAdapter {
  /** Exchange name identifier */
  readonly exchangeName: string;
  
  /** List of supported trading symbols */
  readonly supportedSymbols: string[];
  
  // Market Data Methods
  /**
   * Get current mark price for a symbol
   */
  getMarkPrice(symbol: string): Promise<number>;
  
  /**
   * Get orderbook for a symbol
   */
  getOrderbook(symbol: string): Promise<Orderbook>;
  
  /**
   * Get orderbook depth
   */
  getOrderbookDepth(symbol: string, limit: number): Promise<{ bids: [number, number][], asks: [number, number][] }>;
  
  /**
   * Get recent trades
   */
  getRecentTrades(symbol: string, limit: number): Promise<RawTrade[]>;
  
  /**
   * Get current position for a symbol
   */
  getPosition(symbol: string, markPrice?: number): Promise<Position | null>;
  
  /**
   * Get account balance
   */
  getBalance(): Promise<number>;
  
  // Order Management Methods
  /**
   * Place a limit order
   */
  placeLimitOrder(params: OrderParams): Promise<string>;
  
  /**
   * Cancel an order
   */
  cancelOrder(orderId: string, symbol: string): Promise<boolean>;
  
  /**
   * Cancel all orders for a symbol
   */
  cancelAllOrders(symbol: string): Promise<boolean>;
  
  /**
   * Get open orders for a symbol
   */
  getOpenOrders(symbol: string): Promise<Order[]>;
  
  // Connection Management Methods
  /**
   * Connect to the exchange
   */
  connect(): Promise<void>;
  
  /**
   * Disconnect from the exchange
   */
  disconnect(): Promise<void>;
  
  /**
   * Check if connected to the exchange
   */
  isConnected(): boolean;
  
  /**
   * Get connection health status
   */
  getHealthStatus(): ConnectionHealth;
}

/**
 * State machine interface for managing bot state transitions
 */
export interface IStateMachine {
  /** Current bot state */
  readonly currentState: BotState;
  
  /**
   * Attempt a state transition
   */
  transition(event: StateEvent): Promise<void>;
  
  /**
   * Check if a transition is valid
   */
  canTransition(from: BotState, to: BotState): boolean;
  
  /**
   * Register a state change callback
   */
  onStateChange(callback: (from: BotState, to: BotState, event: StateEvent) => void): void;
  
  /**
   * Get state transition history
   */
  getStateHistory(): StateTransition[];
  
  /**
   * Reset state machine to initial state
   */
  reset(): void;
}

// ============================================================================
// SUPPORTING TYPES
// ============================================================================

/**
 * Order parameters for placing orders
 */
export interface OrderParams {
  /** Trading symbol */
  symbol: string;
  /** Order side */
  side: 'buy' | 'sell';
  /** Order price */
  price: number;
  /** Order size */
  size: number;
  /** Reduce-only flag */
  reduceOnly?: boolean;
  /** Time in force */
  timeInForce?: TimeInForce;
  /** Order type */
  type?: OrderType;
}

/**
 * Connection health status
 */
export interface ConnectionHealth {
  /** Whether connection is healthy */
  isHealthy: boolean;
  /** Last successful ping timestamp */
  lastPing?: Date;
  /** Connection latency in milliseconds */
  latency?: number;
  /** Error message if unhealthy */
  error?: string;
}



/**
 * Strategy status information
 */
export interface StrategyStatus {
  /** Strategy name */
  name: string;
  /** Whether strategy is active */
  isActive: boolean;
  /** Last signal generation timestamp */
  lastSignalTime?: Date;
  /** Number of signals generated */
  signalCount: number;
  /** Strategy performance metrics */
  performance?: {
    winRate: number;
    avgConfidence: number;
    totalSignals: number;
  };
}

/**
 * Filter configuration for strategies
 */
export interface FilterConfig {
  /** Filter type */
  type: string;
  /** Filter parameters */
  parameters: Record<string, any>;
  /** Whether filter is enabled */
  enabled: boolean;
}